baseURL = "https://hsiehmin.com/"
locale = "zh-tw"
defaultContentLanguage = "zh-tw"                             # en / zh-cn / ... (This field determines which i18n file to use)
title = "謝明 - 那些人那些事"
preserveTaxonomyNames = true
enableRobotsTXT = true
enableEmoji = true
theme = "even"
enableGitInfo = false # use git commit log to generate lastmod record # 可根據 Git 中的提交生成最近更新記錄。

# Syntax highlighting by Chroma. NOTE: Don't enable `highlightInClient` and `chroma` at the same time!
pygmentsOptions = "linenos=table"
pygmentsCodefences = true
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true

hasCJKLanguage = true     # has chinese/japanese/korean ? # 自動檢測是否包含 中文\日文\韓文
paginate = 5                                              # 首頁每頁顯示的文章數
disqusShortname = ""      # disqus_shortname
googleAnalytics = ""      # UA-XXXXXXXX-X
copyright = ""            # default: author.name ↓        # 預設為下面配置的author.name ↓


[sitemap]                 # essential                     # 必需
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[[menu.main]]             # config your menu              # 配置目錄
  name = "首頁"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "文章列表"
  weight = 20
  identifier = "archives"
  url = "/post/"
[[menu.main]]
  name = "標籤"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "分類"
  weight = 40
  identifier = "categories"
  url = "/categories/"

[params]
  author = { name = "謝明" }
  version = "4.x"           # Used to give a friendly message when you have an incompatible update
  debug = false             # If true, load `eruda.min.js`. See https://github.com/liriliri/eruda

  since = "2026"            # Site creation time          # 站點建立時間
  # use public git repo url to link lastmod git commit, enableGitInfo should be true.
  # 指定 git 倉庫地址，可以生成指向最近更新的 git commit 的連結，需要將 enableGitInfo 設定成 true.
  gitRepo = ""

  # site info (optional)                                  # 站點資訊（可選，不需要的可以直接註解掉）
  logoTitle = "Hsiehmin"        # default: the title value    # 預設值: 上面設定的 title 值
  favicon = "favicon.svg"
  keywords = ["Hugo", "theme","even"]
  description = "Hugo theme even example site."

  # paginate of archives, tags and categories             # 歸檔、標籤、分類每頁顯示的文章數目，建議修改為一個較大的值
  archivePaginate = 50

  # show 'xx Posts In Total' in archive page ?            # 是否在歸檔頁顯示文章的總數
  showArchiveCount = false

  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "2006-01-02"

  # show word count and read time ?                       # 是否顯示字數統計與閱讀時間
  moreMeta = true

  # show related posts at bottom of the post
  relatedPost = false

  # Syntax highlighting by highlight.js
  highlightInClient = false

  # 一些全域開關，你也可以在每一篇內容的 front matter 中針對單篇內容關閉或開啟某些功能，在 archetypes/default.md 查看更多資訊。
  # Some global options, you can also close or open something in front matter for a single post, see more information from `archetypes/default.md`.
  toc = true                                                                            # 是否開啟目錄
  autoCollapseToc = false   # Auto expand and collapse toc                              # 目錄自動展開/摺疊
  fancybox = true           # see https://github.com/fancyapps/fancybox                 # 是否啟用fancybox（圖片可點擊）

  # mathjax
  mathjax = false           # see https://www.mathjax.org/                              # 是否使用mathjax（數學公式）
  mathjaxEnableSingleDollar = false                                                     # 是否使用 $...$ 即可進行inline latex渲染
  mathjaxEnableAutoNumber = false                                                       # 是否使用公式自動編號
  mathjaxUseLocalFiles = false  # You should install mathjax in `your-site/static/lib/mathjax`

  postMetaInFooter = true   # contain author, lastMod, markdown link, license           # 包含作者，上次修改時間，markdown連結，許可資訊
  linkToMarkDown = false    # Only effective when hugo will output .md files.           # 連結到markdown原始檔案（僅當允許hugo生成markdown檔案時有效）
  contentCopyright = ''     # e.g. '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'

  googleVerification = ""  # Google Verification         # 谷歌

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  customCSS = []
  customJS = []

  uglyURLs = false          # please keep same with uglyurls setting

  # Show language selector for multilingual site.
  showLanguageSelector = false

  # Hide the mobile navbar while scrolling down, and show it while scrolling up.
  [params.mobileNavbar]
    hideOnScroll = true

  [params.publicCDN]        # load these files from public cdn                          # 啟用公共CDN，需自行定義
    enable = true
    jquery = '<script src="https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>'
    slideout = '<script src="https://cdn.jsdelivr.net/npm/slideout@1.0.1/dist/slideout.min.js" integrity="sha256-t+zJ/g8/KXIJMjSVQdnibt4dlaDxc9zXr/9oNPeWqdg=" crossorigin="anonymous"></script>'
    fancyboxJS = '<script src="https://cdn.jsdelivr.net/npm/@fancyapps/ui@4.0/dist/fancybox.umd.js"></script>'
    fancyboxCSS = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/ui/dist/fancybox.css">'
    timeagoJS = '<script src="https://cdn.jsdelivr.net/npm/timeago.js@3.0.2/dist/timeago.min.js" integrity="sha256-jwCP0NAdCBloaIWTWHmW4i3snUNMHUNO+jr9rYd2iOI=" crossorigin="anonymous"></script>'
    timeagoLocalesJS = '<script src="https://cdn.jsdelivr.net/npm/timeago.js@3.0.2/dist/timeago.locales.min.js" integrity="sha256-ZwofwC1Lf/faQCzN7nZtfijVV6hSwxjQMwXL4gn9qU8=" crossorigin="anonymous"></script>'
    flowchartDiagramsJS = '<script src="https://cdn.jsdelivr.net/npm/raphael@2.2.7/raphael.min.js" integrity="sha256-67By+NpOtm9ka1R6xpUefeGOY8kWWHHRAKlvaTJ7ONI=" crossorigin="anonymous"></script> <script src="https://cdn.jsdelivr.net/npm/flowchart.js@1.8.0/release/flowchart.min.js" integrity="sha256-zNGWjubXoY6rb5MnmpBNefO0RgoVYfle9p0tvOQM+6k=" crossorigin="anonymous"></script>'
    sequenceDiagramsCSS = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/bramp/js-sequence-diagrams@2.0.1/dist/sequence-diagram-min.css" integrity="sha384-6QbLKJMz5dS3adWSeINZe74uSydBGFbnzaAYmp+tKyq60S7H2p6V7g1TysM5lAaF" crossorigin="anonymous">'
    sequenceDiagramsJS = '<script src="https://cdn.jsdelivr.net/npm/webfontloader@1.6.28/webfontloader.js" integrity="sha256-4O4pS1SH31ZqrSO2A/2QJTVjTPqVe+jnYgOWUVr7EEc=" crossorigin="anonymous"></script> <script src="https://cdn.jsdelivr.net/npm/snapsvg@0.5.1/dist/snap.svg-min.js" integrity="sha256-oI+elz+sIm+jpn8F/qEspKoKveTc5uKeFHNNVexe6d8=" crossorigin="anonymous"></script> <script src="https://cdn.jsdelivr.net/npm/underscore@1.8.3/underscore-min.js" integrity="sha256-obZACiHd7gkOk9iIL/pimWMTJ4W/pBsKu+oZnSeBIek=" crossorigin="anonymous"></script> <script src="https://cdn.jsdelivr.net/gh/bramp/js-sequence-diagrams@2.0.1/dist/sequence-diagram-min.js" integrity="sha384-8748Vn52gHJYJI0XEuPB2QlPVNUkJlJn9tHqKec6J3q2r9l8fvRxrgn/E5ZHV0sP" crossorigin="anonymous"></script>'

  # Display a message at the beginning of an article to warn the readers that it's content may be outdated.
  # 在文章開頭顯示提示資訊，提醒讀者文章內容可能過時。
  [params.outdatedInfoWarning]
    enable = false
    hint = 30               # Display hint if the last modified time is more than these days ago.    # 如果文章最後更新於這天數之前，顯示提醒
    warn = 180              # Display warning if the last modified time is more than these days ago.    # 如果文章最後更新於這天數之前，顯示警告

  [params.gitment]          # Gitment is a comment system based on GitHub issues. see https://github.com/imsun/gitment
    owner = ""              # Your GitHub ID
    repo = ""               # The repo to store comments
    clientId = ""           # Your client ID
    clientSecret = ""       # Your client secret

  [params.utterances]       # https://utteranc.es/
    enable = false
    owner = ""              # Your GitHub ID
    repo = ""               # The repo to store comments

  [params.gitalk]           # Gitalk is a comment system based on GitHub issues. see https://github.com/gitalk/gitalk
    owner = ""              # Your GitHub ID
    repo = ""               # The repo to store comments
    clientId = ""           # Your client ID
    clientSecret = ""       # Your client secret

  [params.waline]
    enable = true
    serverURL = "https://blog-comment-weld-theta.vercel.app"
    lang = "zh-TW"

  [params.flowchartDiagrams]# see https://blog.olowolo.com/example-site/post/js-flowchart-diagrams/
    enable = false
    options = ""

  [params.sequenceDiagrams] # see https://blog.olowolo.com/example-site/post/js-sequence-diagrams/
    enable = false
    options = ""            # default: "{theme: 'simple'}"

  # [params.social]                                         # 社交連結
  #   a-email = "mailto:your@email.com"
  #   b-stack-overflow = "http://localhost:1313"
  #   c-twitter = "http://localhost:1313"
  #   d-facebook = "http://localhost:1313"
  #   e-linkedin = "http://localhost:1313"
  #   f-google = "http://localhost:1313"
  #   g-github = "http://localhost:1313"
  #   h-weibo = "http://localhost:1313"
  #   i-zhihu = "http://localhost:1313"
  #   j-douban = "http://localhost:1313"
  #   k-pocket = "http://localhost:1313"
  #   l-tumblr = "http://localhost:1313"
  #   m-instagram = "http://localhost:1313"
  #   n-gitlab = "http://localhost:1313"
  #   o-bilibili = "http://localhost:1313"

# See https://gohugo.io/about/hugo-and-gdpr/
[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true      # 12.214.31.144 -> 12.214.31.0
  [privacy.youtube]
    privacyEnhanced = true

# see https://gohugo.io/getting-started/configuration-markup
[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 2
  [markup.goldmark.renderer]
    unsafe = true

# 將下面這段配置取消註解可以使 hugo 生成 .md 檔案
# Uncomment these options to make hugo output .md files.
#[mediaTypes]
#  [mediaTypes."text/plain"]
#    suffixes = ["md"]
#
#[outputFormats.MarkDown]
#  mediaType = "text/plain"
#  isPlainText = true
#  isHTML = false
#
#[outputs]
#  home = ["HTML", "RSS"]
#  page = ["HTML", "MarkDown"]
#  section = ["HTML", "RSS"]
#  taxonomy = ["HTML", "RSS"]
#  taxonomyTerm = ["HTML"]
